### ISSUE TITLE
Recon module failing at /usr/share/fruitywifi/www/modules/recon/www.recon/sql.php(23): 

### ISSUE THREAD

**Issue by LucaBongiorni** [xtr4nge/FruityWifi#146]
Env.= RPi2 + Kali + FruityWifi 2.2 + All modules + AR9721
Version of php5-sqlite is from repos 5.4.41-0+deb7u1
As you can see from error logs below recon is hanging when is trying to execute sql.php.

2015/07/22 12:03:32 [error] 1969#0: *11 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'PDOException' with message 'could$
Stack trace:
#0 /usr/share/fruitywifi/www/modules/recon/www.recon/sql.php(23): PDO->__construct('sqlite:db/db.sq...')
#1 /usr/share/fruitywifi/www/modules/recon/www.recon/sql.php(181): createDB()
#2 {main}
  thrown in /usr/share/fruitywifi/www/modules/recon/www.recon/sql.php on line 23" while reading response header from upstream, client: 10.0.0.1, serv$
2015/07/22 12:08:10 [error] 1969#0: *14 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'PDOException' with message 'could$
Stack trace:
#0 /usr/share/fruitywifi/www/modules/recon/www.recon/sql.php(23): PDO->__construct('sqlite:db/db.sq...')
#1 /usr/share/fruitywifi/www/modules/recon/www.recon/sql.php(181): createDB()
#2 {main}
  thrown in /usr/share/fruitywifi/www/modules/recon/www.recon/sql.php on line 23" while reading response header from upstream, client: 10.0.0.1, serv$
2015/07/22 12:08:13 [error] 1969#0: *14 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'PDOException' with message 'could$
Stack trace:
#0 /usr/share/fruitywifi/www/modules/recon/www.recon/sql.php(23): PDO->__construct('sqlite:db/db.sq...')
#1 /usr/share/fruitywifi/www/modules/recon/www.recon/sql.php(181): createDB()
#2 {main}
  thrown in /usr/share/fruitywifi/www/modules/recon/www.recon/sql.php on line 23" while reading response header from upstream, client: 10.0.0.1, serv$
2015/07/22 12:09:10 [error] 1969#0: *14 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'PDOException' with message 'could$
Stack trace:
#0 /usr/share/fruitywifi/www/modules/recon/www.recon/sql.php(23): PDO->__construct('sqlite:db/db.sq...')
#1 /usr/share/fruitywifi/www/modules/recon/www.recon/sql.php(181): createDB()
#2 {main}
  thrown in /usr/share/fruitywifi/www/modules/recon/www.recon/sql.php on line 23" while reading response header from upstream, client: 10.0.0.1, serv$

**Comment by xtr4nge** [comment]
Hi LucaBongiorni, 
Thanks for reporting this issue. I will take a look asap ;)

regards,
