### ISSUE TITLE
Modules Install issues

### ISSUE THREAD

**Issue by CarbonNos** [xtr4nge/FruityWifi#192]
Hi, i've installed FruityWifi on my Kali 2016 but when i install modules i receive this error.

root@kali:~/FruityWifi# python install-modules.py
Traceback (most recent call last):
  File "install-modules.py", line 34, in <module>
    url = urllib2.urlopen("https://raw.githubusercontent.com/xtr4nge/FruityWifi/master/modules-FruityWifi.xml")
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>

**Comment by xtr4nge** [comment]
Hi CarbonNos,
I just did a clean install using a Kali Linux Rolling live CD, and everything works fine.
You need to have internet access, and you need FrutiyWiFi installed first.

(as root)
- wget https://github.com/xtr4nge/FruityWifi/archive/master.zip
- unzip FruityWifi-master.zip
- cd FruityWifi-master
- ./install-FruityWifi.sh
- ./install-modules.sh

regards,
