### ISSUE TITLE
When I running “install-modules.py” there are some python related issues

### ISSUE THREAD

**Issue by ixiusama** [xtr4nge/FruityWifi#221]
Terminal display
```
File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead

```
I do not understand how to fix it

The following is the whole process of my operation
```
sudo wget https://github.com/xtr4nge/FruityWifi/archive/master.zip

sudo unzip master.zip

sudo cd FruityWifi-master/

sudo chmod 755 ./install-FruityWifi.sh

sudo ./install-FruityWifi.sh

sudo ./install-modules.py
```

**Comment by xtr4nge** [comment]
Hi ixiusama,
If you are new with FruityWiFi, I recommend to install the modules from the web interface one by one after get FruityWiFi working. There are more than 50 modules now and many interdependencies between them, so using install-modules.py it is not anymore a good option for the moment.
Just go to the web-interface FruityWiFi/menu/modules and install the modules that you want. (API and AP are the primary modules)

Note: on Kali Linux, you need to use the installer for PHP7. For Debian use the standard installer.

regards,
