### ISSUE TITLE
Modules Not installing

### ISSUE THREAD

**Issue by H4xl0r** [xtr4nge/FruityWifi#268]
Installed via Setup script on raspi.
webinterface shows up but im not able to load the modules
when running install modules :

```
:/home/pi/FruityWifi-master# ./install-modules.py
Traceback (most recent call last):
  File "./install-modules.py", line 34, in <module>
    url = urllib2.urlopen("http://raw.githubusercontent.com/xtr4nge/FruityWifi/master/modules-FruityWifi.xml")
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>

```
ANY HELP ?

**Comment by H4xl0r** [comment]
update ssl certs on linux 
sudo update-ca-certificates --fresh
